publishdir = "docs"
enableEmoji = true
  
baseurl = "https://web-work.tools/indieweb/"
title = "An exploration of the IndieWebiverse"
copyright = "⧉ Infominer ⧉ CC0 - Public Domain ⧉ Powered by: themes.gohugo.io/indigo via: gohugoio/hugo ⧉"
languageCode = "en-gb"
theme = "indigo"
paginate = 8

[params]
  Author = "Infominer"
  description = "Static Sites for an IndieWeb"
  Subtitle = "Principles, Practice, and Documentation"
  Avatar = "images/infominer.svg"
  Biography = "Full-Time Independent Web-Worker. Research, Skyscraper Publishing, IndieWeb ⧉ Crypto-Curation and Histories ⧉ Bitcoin, Blockchain, DecentralizedID ⧉ her/him"
  ShowBio = true
  PermalinkText = "🔗"
  images = "https://web-work.tools/indieweb/images/indieweb.jpg"

  # Contact/social-network identifiers for social icons
  EmailAddress = "infominer@protonmail.com"
  GitHubUser = "infominer33"
  GitLabUser = "infominer33"
  KeybaseUser = "infominer"
  MicroBlogUser = "infominer"
  RedditUser = "infominer33"
  StackOverflowUser = "10793272"
  TwitterUser = "infominer33"

  # These are parameters used for indieweb identity. You should set these along
  # with the above email/social network parameters.
  [params.indieWeb]  
    EmailAddress = "infominer@protonmail.com"
    GitHubUser = "infominer33"
    TwitterUser = "infominer33"
    MicroBlogUser = "infominer"
    Country = "49 6e 64 75 73"
    City = "Mehtab Bagh"

[Social]
  twitter = "infominer33"

#https://github.com/kisik21/indigo/commit/e168672487b78bef5070cc0eb70bc5d4e748c707
  [params.endpoints]
  Auth = "https://indieauth.com/auth"
  # To get webmention support, just register at webmention.io and paste the link for endpoint here.
  Webmention = "https://webmention.io/web-work.tools_indieweb_/webmention"
  # To get micropub support, you'll need to install a Micropub endpoint at your site and put its link there.
  # To get an endpoint with Hugo support, use nanopub: https://github.com/dg01d/nanopub
  # It will probably require some PHP hackery though, as it's fairly basic.
  #Micropub = ""
  # To get microsub support, you can use Aperture from p3k. Either go to https://aperture.p3k.io or self-host it (it's open source!)
  #Microsub = ""

disablePathToLower = true

[Permalinks]
  posts = "/:slug/"